version: '2'
services:
  web-service:
    build: .
    depends_on:
      - postgresql
      - rabbit
      - workers
      - front-end
    container_name: web-service
    links:
      - postgresql
      - rabbit
    ports:
      - 8000:8000
    volumes:
      - .:/app/
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

  workers:
    build: .
    depends_on:
      - postgresql
      - rabbit
    container_name: workers
    links:
      - postgresql
      - rabbit
    volumes:
      - .:/app/
    command: >
      sh -c "celery -A PortScanner worker -l INFO"

  front-end:
    build: ./front-end
    container_name: front-end
    volumes:
      - ./front-end:/app/
    command: >
      sh -c "npm start"
    ports:
      - 3000:3000



  rabbit:
    container_name: rabbit
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672

  postgresql:
    container_name: postgresql
    restart: always
    image: postgres:11.7-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=port_scanner
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432


volumes:
  postgres-data: