# Generated by Django 3.1.6 on 2021-02-07 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip',
            name='custom_ports',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
