# Generated by Django 3.1.6 on 2021-02-07 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0004_auto_20210207_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='port_number',
            field=models.PositiveIntegerField(),
        ),
    ]
